### ISSUE TITLE
[Fatal] Broken build system

### ISSUE THREAD

**Issue by kyasbal-1994** [GrimoireGL/GrimoireJS#394]
~~Replace environment for development with System.js and jspm.~~

**~~Tasks~~**
**Cancelled**
* [x] System.js調査/jspm調査
* [x] Typescript相互運用の問題調査
* [x] grimoirejsの移行(https://github.com/GrimoireGL/GrimoireJS/tree/jspm)
* [ ] grimoirejs-fundamentalの移行
* [ ] index.tsの自動挿入プログラムの移植
* [ ] プロジェクトテンプレートの作成
* [ ] 旧ビルドシステムの現行プロジェクトからの削除

**~~Problems~~**
**Cancelled**
* [x] Typescriptのd.tsをうまく参照できるのか(npm installとjspm installを両方行う必要がある)
* [x] babel後のポリフィル関係
* [ ] テキストファイル問題(ts側で`*!text`に対してのインターフェースの作成、System.js側のtextプラグインを用いれば良い)
* [ ] プラグインの読み込み開始タイミングの問題

**Specifications**

## Plugin publishment policy

~~All plugin packages should contains `lib` folder which is containing ES5 javascript files.
One of the file contained in that folder should specified as `main` in package.json.~~

~~When the package was written with Typescript, `lib` folder must be contained in published files.
That folder must contain all of *.d.ts files for definitions and one of them should specified as `typings` in package.json. 
(Declaration folder and javascript folder can't be separated to be able to access scripts of package by `PACKAGENAME/lib/MODULENNAME` syntax.)~~

~~Even plugin publisher didn't use System.js or jspm, if this structure is keeped, users can easily access all plugins.~~

**Comment by kyasbal-1994** [comment]
# ビルド環境の修正

堅牢で維持可能なビルド環境の作成。

**大事なこと**

上の方が優先度が高いと考えられる項目

* プラグイン使用者は簡易な手順でプラグインを導入できるか?
* プラグイン作者、こちらの製作陣が同じビルド環境を用いれるか?
(複数種類のビルド環境を持つことはリスクが高くメンテナンスがしにくい)
* Typescript環境を選択でき、型の恩恵を受けながらプラグインの開発が可能か?

**手法**

* 上記要件の1番目を鑑みると、ユーザーは`script`タグで使いたいプラグインを選択できると良い。
(プラグインの数だけscriptタグが増えるのはあまり行けてない気がするが、その場合はバンドリングすればいいだろうし、大した問題ではないだろう。)
* 一方でnpmから使いたい人のために各インターフェースを露出すると良い。
(scriptから読み込んだ場合があくまで優先)
* ES6にコンパイル済み(あるいはES6で書かれた)のファイル群から、自動で露出するためのimportなどを生成する。

**Comment by kyasbal-1994** [comment]
**ユーザー側のimportの手法**

**grimoirejs内のクラスを取得する場合**

grimoirejs内の`PATH/TO/YYY`にアクセスする場合

1. scriptタグにより挿入された場合の解決手法

```
const target = gr.PATH.TO.YYY;
```

2. ES6記法でモジュールとして扱う場合

```
import gr from "grimoirejs";
const target = gr.PATH.TO.YYY;
```

**grimoirejs-ZZZの`PATH/TO/YYY`を取得する場合**

1. scriptタグにより導入された場合

```
const target = gr.lib.ZZZ.PATH.TO.YYY;
```

2. ES6記法で行う場合

```
import grZ from "grimoirejs-ZZZ";
const target = grZ.PATH.TO.YYY;
```

ただし、この`grZ｀はgr.lib.ZZZ;であるべきであり、`grZ === gr.lib.ZZZ`となるべきである。

**実際の解決手段**

1. grimoirejsは自身の全クラスファイルをgr以下に露出する。

現状では`gr === GrimoireInterface`であるが、gr以下に全てのクラスファイルを階層構造をオブジェクトとして分割して配置しても、フォルダ名が大文字から始まること、クラスメンバに大文字から始まる要素はないことから実際のメソッド名とフォルダ名その他requireされる対象がコンフリクトすることはありえない。

2. grimoirejs-ZZZは、importするとデフォルトexportとして自身の全クラスファイルを露出したものを返す。
(ただし、同時にプラグインとしてgr本体側に登録する処理も行う。この際、gr.lib.(ライブラリ名)に対して自身のdefaultエクスポートを代入する)

**Comment by kyasbal-1994** [comment]
あくまで例であるがgrimoirejs-cauldronの中にこの参照を生成するスクリプトを作ってみた。

https://github.com/GrimoireGL/grimoirejs-cauldron/blob/master/src/generate-index/generate-index.js

参考にして欲しい。

**Comment by pnlybubbles** [comment]
jsのエントリを生成するのではなくてtsのエントリを生成するのでは？

**Comment by kyasbal-1994** [comment]
それだと、ES6そのまま書く場合には別のビルド環境が必要になる。

**Comment by kyasbal-1994** [comment]
あくまで、ES6のフォルダを指定するとその処理を行ってバンドリングするということにしといて、TSの場合はそのES6のフォルダに書き出す形で処理すれば良いと思う

**Comment by pnlybubbles** [comment]
d.tsが生成できない点はどのように対応？
ts用とes用と別々に作る方がベターな気がします。

**Comment by kyasbal-1994** [comment]
d.tsも吐き出せばいいのでは?ES6で書かれる場合もanyとしたd.tsを作ってあげないと、typescriptで扱う人からしたら困るので、どちらにしてもd.tsは必要だと思う。

**Comment by kyasbal-1994** [comment]
現状の進捗

jsについてはほぼどうにかなる見通しは立った。d.tsに関しては関数やインターフェースのexposeの問題があったが、これに関してはTypescriptの`Type Queries`なる文法を用いたら回避ができた。(参考 https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.8.10)

テキストファイルとの連携どうするのか問題、Webpackなどの導入どうするのか問題を考えると、もういっそ最初からWebpack部分に導入したいところ。これもやっぱり自分でやることにしてみる。明日中には。。。。

```
  import AssetAssetLoader from "./Asset/AssetLoader";
  import AssetCacheResolver from "./Asset/CacheResolver";
  import AssetdefaultLoader_html from "./Asset/defaultLoader.html";
  import AssetExternalResourceResolver from "./Asset/ExternalResourceResolver";
  import AssetImageResolver from "./Asset/ImageResolver";
  import AssetTextFileResolver from "./Asset/TextFileResolver";
  import CameraPerspectiveCamera from "./Camera/PerspectiveCamera";
  import ComponentsAssetLoadingManagerComponent from "./Components/AssetLoadingManagerComponent";
  import ComponentsCameraComponent from "./Components/CameraComponent";
  import ComponentsCanvasInitializerComponent from "./Components/CanvasInitializerComponent";
  import ComponentsFullscreenComponent from "./Components/FullscreenComponent";
  import ComponentsGeometryComponent from "./Components/GeometryComponent";
  import ComponentsGeometryRegistoryComponent from "./Components/GeometryRegistoryComponent";
  import ComponentsHTMLBinderComponent from "./Components/HTMLBinderComponent";
  import ComponentsLoopManagerComponent from "./Components/LoopManagerComponent";
  import ComponentsMaterialComponent from "./Components/MaterialComponent";
  import ComponentsMaterialContainerComponent from "./Components/MaterialContainerComponent";
  import ComponentsMaterialImporterComponent from "./Components/MaterialImporterComponent";
  import ComponentsMaterialManagerComponent from "./Components/MaterialManagerComponent";
  import ComponentsMeshRendererComponent from "./Components/MeshRendererComponent";
  import ComponentsMouseCameraControlComponent from "./Components/MouseCameraControlComponent";
  import ComponentsRenderBufferComponent from "./Components/RenderBufferComponent";
  import ComponentsRendererComponent from "./Components/RendererComponent";
  import ComponentsRendererManagerComponent from "./Components/RendererManagerComponent";
  import ComponentsRenderQuadComponent from "./Components/RenderQuadComponent";
  import ComponentsRenderSceneComponent from "./Components/RenderSceneComponent";
  import ComponentsSceneComponent from "./Components/SceneComponent";
  import ComponentsTextureBufferComponent from "./Components/TextureBufferComponent";
  import ComponentsTextureComponent from "./Components/TextureComponent";
  import ComponentsTransformComponent from "./Components/TransformComponent";
  import ConstraintChildrenComponentConstraint from "./Constraint/ChildrenComponentConstraint";
  import ConstraintNoChildConstraint from "./Constraint/NoChildConstraint";
  import ConstraintParentConstraint from "./Constraint/ParentConstraint";
  import ConstraintRootConstraint from "./Constraint/RootConstraint";
  import ConvertersAngle2DConverter from "./Converters/Angle2DConverter";
  import ConvertersBooleanConverter from "./Converters/BooleanConverter";
  import ConvertersCanvasSizeConverter from "./Converters/CanvasSizeConverter";
  import ConvertersColor3Converter from "./Converters/Color3Converter";
  import ConvertersColor4Converter from "./Converters/Color4Converter";
  import ConvertersComponentConverter from "./Converters/ComponentConverter";
  import ConvertersEnumConverter from "./Converters/EnumConverter";
  import ConvertersGeometryConverter from "./Converters/GeometryConverter";
  import ConvertersMaterialConverter from "./Converters/MaterialConverter";
  import ConvertersNumberArrayConverter from "./Converters/NumberArrayConverter";
  import ConvertersNumberConverter from "./Converters/NumberConverter";
  import ConvertersObjectConverter from "./Converters/ObjectConverter";
  import ConvertersRotation3Converter from "./Converters/Rotation3Converter";
  import ConvertersStringArrayConverter from "./Converters/StringArrayConverter";
  import ConvertersStringConverter from "./Converters/StringConverter";
  import ConvertersTexture2DConverter from "./Converters/Texture2DConverter";
  import ConvertersTextureConverter from "./Converters/TextureConverter";
  import ConvertersVector2Converter from "./Converters/Vector2Converter";
  import ConvertersVector3Converter from "./Converters/Vector3Converter";
  import ConvertersVector4Converter from "./Converters/Vector4Converter";
  import ConvertersViewportConverter from "./Converters/ViewportConverter";
  import GeometryDefaultPrimitives from "./Geometry/DefaultPrimitives";
  import GeometryGeometry from "./Geometry/Geometry";
  import GeometryGeometryBuilder from "./Geometry/GeometryBuilder";
  import GeometryGeometryFactory from "./Geometry/GeometryFactory";
  import GeometryGeometryUtility from "./Geometry/GeometryUtility";
  import MaterialDefaultMacro from "./Material/DefaultMacro";
  import MaterialDefaultMaterial from "./Material/DefaultMaterial";
  import MaterialEnvUniformValueResolver from "./Material/EnvUniformValueResolver";
  import MaterialImportResolver from "./Material/ImportResolver";
  import MaterialMacroRegistory from "./Material/MacroRegistory";
  import MaterialMaterial from "./Material/Material";
  import MaterialMaterialFactory from "./Material/MaterialFactory";
  import MaterialPass from "./Material/Pass";
  import MaterialPassFactory from "./Material/PassFactory";
  import MaterialSORTPass from "./Material/SORTPass";
  import MaterialStaticheader_glsl from "./Material/Static/header.glsl";
  import MaterialStaticUnlit_Color_sort from "./Material/Static/Unlit-Color.sort";
  import MaterialStaticUnlit_Textured_sort from "./Material/Static/Unlit-Textured.sort";
  import MaterialStaticUnlit_sort from "./Material/Static/Unlit.sort";
  import MaterialTextureReference from "./Material/TextureReference";
  import MaterialTransformersAnnotationRemover from "./Material/Transformers/AnnotationRemover";
  import MaterialTransformersCommentRemover from "./Material/Transformers/CommentRemover";
  import MaterialTransformersGLSLUtil from "./Material/Transformers/GLSLUtil";
  import MaterialTransformersImportTransformer from "./Material/Transformers/ImportTransformer";
  import MaterialTransformersPreferenceParser from "./Material/Transformers/PreferenceParser";
  import MaterialTransformersSORTPassParser from "./Material/Transformers/SORTPassParser";
  import MaterialTransformersUniformRegisterer from "./Material/Transformers/UniformRegisterer";
  import MaterialTransformersVariableAnnotationRemover from "./Material/Transformers/VariableAnnotationRemover";
  import MaterialTransformersVariableParser from "./Material/Transformers/VariableParser";
  import ResourceBuffer from "./Resource/Buffer";
  import ResourceFrameBuffer from "./Resource/FrameBuffer";
  import ResourceGLExtRequestor from "./Resource/GLExtRequestor";
  import ResourceProgram from "./Resource/Program";
  import ResourceRenderBuffer from "./Resource/RenderBuffer";
  import ResourceResourceBase from "./Resource/ResourceBase";
  import ResourceShader from "./Resource/Shader";
  import ResourceTexture2D from "./Resource/Texture2D";
  import ResourceUniformProxy from "./Resource/UniformProxy";
  import UtilRotationParser from "./Util/RotationParser";

interface Expose{
  "Asset": {
    "AssetLoader": typeof AssetAssetLoader;
    "CacheResolver": typeof AssetCacheResolver;
    "defaultLoader.html": typeof AssetdefaultLoader_html;
    "ExternalResourceResolver": typeof AssetExternalResourceResolver;
    "ImageResolver": typeof AssetImageResolver;
    "TextFileResolver": typeof AssetTextFileResolver;
  };
  "Camera": {
    "PerspectiveCamera": typeof CameraPerspectiveCamera;
  };
  "Components": {
    "AssetLoadingManagerComponent": typeof ComponentsAssetLoadingManagerComponent;
    "CameraComponent": typeof ComponentsCameraComponent;
    "CanvasInitializerComponent": typeof ComponentsCanvasInitializerComponent;
    "FullscreenComponent": typeof ComponentsFullscreenComponent;
    "GeometryComponent": typeof ComponentsGeometryComponent;
    "GeometryRegistoryComponent": typeof ComponentsGeometryRegistoryComponent;
    "HTMLBinderComponent": typeof ComponentsHTMLBinderComponent;
    "LoopManagerComponent": typeof ComponentsLoopManagerComponent;
    "MaterialComponent": typeof ComponentsMaterialComponent;
    "MaterialContainerComponent": typeof ComponentsMaterialContainerComponent;
    "MaterialImporterComponent": typeof ComponentsMaterialImporterComponent;
    "MaterialManagerComponent": typeof ComponentsMaterialManagerComponent;
    "MeshRendererComponent": typeof ComponentsMeshRendererComponent;
    "MouseCameraControlComponent": typeof ComponentsMouseCameraControlComponent;
    "RenderBufferComponent": typeof ComponentsRenderBufferComponent;
    "RendererComponent": typeof ComponentsRendererComponent;
    "RendererManagerComponent": typeof ComponentsRendererManagerComponent;
    "RenderQuadComponent": typeof ComponentsRenderQuadComponent;
    "RenderSceneComponent": typeof ComponentsRenderSceneComponent;
    "SceneComponent": typeof ComponentsSceneComponent;
    "TextureBufferComponent": typeof ComponentsTextureBufferComponent;
    "TextureComponent": typeof ComponentsTextureComponent;
    "TransformComponent": typeof ComponentsTransformComponent;
  };
  "Constraint": {
    "ChildrenComponentConstraint": typeof ConstraintChildrenComponentConstraint;
    "NoChildConstraint": typeof ConstraintNoChildConstraint;
    "ParentConstraint": typeof ConstraintParentConstraint;
    "RootConstraint": typeof ConstraintRootConstraint;
  };
  "Converters": {
    "Angle2DConverter": typeof ConvertersAngle2DConverter;
    "BooleanConverter": typeof ConvertersBooleanConverter;
    "CanvasSizeConverter": typeof ConvertersCanvasSizeConverter;
    "Color3Converter": typeof ConvertersColor3Converter;
    "Color4Converter": typeof ConvertersColor4Converter;
    "ComponentConverter": typeof ConvertersComponentConverter;
    "EnumConverter": typeof ConvertersEnumConverter;
    "GeometryConverter": typeof ConvertersGeometryConverter;
    "MaterialConverter": typeof ConvertersMaterialConverter;
    "NumberArrayConverter": typeof ConvertersNumberArrayConverter;
    "NumberConverter": typeof ConvertersNumberConverter;
    "ObjectConverter": typeof ConvertersObjectConverter;
    "Rotation3Converter": typeof ConvertersRotation3Converter;
    "StringArrayConverter": typeof ConvertersStringArrayConverter;
    "StringConverter": typeof ConvertersStringConverter;
    "Texture2DConverter": typeof ConvertersTexture2DConverter;
    "TextureConverter": typeof ConvertersTextureConverter;
    "Vector2Converter": typeof ConvertersVector2Converter;
    "Vector3Converter": typeof ConvertersVector3Converter;
    "Vector4Converter": typeof ConvertersVector4Converter;
    "ViewportConverter": typeof ConvertersViewportConverter;
  };
  "Geometry": {
    "DefaultPrimitives": typeof GeometryDefaultPrimitives;
    "Geometry": typeof GeometryGeometry;
    "GeometryBuilder": typeof GeometryGeometryBuilder;
    "GeometryFactory": typeof GeometryGeometryFactory;
    "GeometryUtility": typeof GeometryGeometryUtility;
  };
  "Material": {
    "DefaultMacro": typeof MaterialDefaultMacro;
    "DefaultMaterial": typeof MaterialDefaultMaterial;
    "EnvUniformValueResolver": typeof MaterialEnvUniformValueResolver;
    "ImportResolver": typeof MaterialImportResolver;
    "MacroRegistory": typeof MaterialMacroRegistory;
    "Material": typeof MaterialMaterial;
    "MaterialFactory": typeof MaterialMaterialFactory;
    "Pass": typeof MaterialPass;
    "PassFactory": typeof MaterialPassFactory;
    "SORTPass": typeof MaterialSORTPass;
    "Static": {
      "header.glsl": typeof MaterialStaticheader_glsl;
      "Unlit-Color.sort": typeof MaterialStaticUnlit_Color_sort;
      "Unlit-Textured.sort": typeof MaterialStaticUnlit_Textured_sort;
      "Unlit.sort": typeof MaterialStaticUnlit_sort;
    };
    "TextureReference": typeof MaterialTextureReference;
    "Transformers": {
      "AnnotationRemover": typeof MaterialTransformersAnnotationRemover;
      "CommentRemover": typeof MaterialTransformersCommentRemover;
      "GLSLUtil": typeof MaterialTransformersGLSLUtil;
      "ImportTransformer": typeof MaterialTransformersImportTransformer;
      "PreferenceParser": typeof MaterialTransformersPreferenceParser;
      "SORTPassParser": typeof MaterialTransformersSORTPassParser;
      "UniformRegisterer": typeof MaterialTransformersUniformRegisterer;
      "VariableAnnotationRemover": typeof MaterialTransformersVariableAnnotationRemover;
      "VariableParser": typeof MaterialTransformersVariableParser;
    };
  };
  "Resource": {
    "Buffer": typeof ResourceBuffer;
    "FrameBuffer": typeof ResourceFrameBuffer;
    "GLExtRequestor": typeof ResourceGLExtRequestor;
    "Program": typeof ResourceProgram;
    "RenderBuffer": typeof ResourceRenderBuffer;
    "ResourceBase": typeof ResourceResourceBase;
    "Shader": typeof ResourceShader;
    "Texture2D": typeof ResourceTexture2D;
    "UniformProxy": typeof ResourceUniformProxy;
  };
  "Util": {
    "RotationParser": typeof UtilRotationParser;
  };
};

export default Expose;
```

**Comment by kyasbal-1994** [comment]
現状存在する特殊なビルドタスクは3つ

* テキストファイルなどの適当なd.tsファイルを生成しているタスク
* コンポーネントのregisterを自動で行うコードをindex.tsに生成するタスク(必要?不要?)
* 上記の外部へのExposeを行うファイルを生成するタスク

**Comment by kyasbal-1994** [comment]
バンドリング時にexcludeって本当にできるっけ問題

**Comment by kyasbal-1994** [comment]
モジュールのディレクトリ構成

npmでの解決の場合、以下の2つのエントリーポイントが考えられる。

* register.js
* index.js

もし、ユーザーがgrimoirejsのモジュールを解決するなら、あるgrimoirejsのインポートによってgrimoirejs全体がバンドリングされうる問題に注意を払う必要がある。
しかし、実際には、(特にプラグインの作成時には)、その参照だけが欲しいのであって、対象をバンドリングに含めることを指示することには問題がある。

そのため、各モジュールは以下のようなファイルをそれぞれ含む。
以下の例は、`grimoirejs-ZZZ`なるプラグインにおけるindex.jsの記述の例である。

**index.js**
package.jsonのmainに指定されるべきファイルである。これによって取得されるjsはあくまで以下のような形式をとる。
```
export default window.GrimoireJS.default.Lib.ZZZ;
```

これであれば、あくまで取って来ている参照は自身によって登録された対象であって、もしscriptタグなどであらかじめ読み込まれているような場合であっても、このスクリプトではバンドリング対象に含まれず対象が取得できる。

一方で、そもそも登録が目的の場合もありうる。

**register/index.js**

実際にタグの登録など、ライブラリ本体はこちらを読み込む必要がある。
ここには生成された外部公開用のオブジェクトが含まれる。

**Comment by kyasbal-1994** [comment]
d.tsを生成する方法は難しい。d.tsはあくまで定義ファイルなので、それを用いるクラスでimportされていない限りexportはできない。tsを生成する方法を別に用意する必要がある。

**Comment by kyasbal-1994** [comment]
オブジェクトに代入する方式では、Typescriptはそこから型として解釈することがないため、プラグイン製作側での利用が問題になる。どうしたら良いか。

**Comment by kyasbal-1994** [comment]
importされない型はうまくTSで認識されない。したがって変数に型定義を代入してそれを継承したりすることも難しい。
以下のような解決はどうか?

```typescript
export default window.GrimoireJS.lib.Path.To.Module;
```
のようなjsファイルに対して、ついになるd.tsは実際の型定義を用いる。

**Comment by pnlybubbles** [comment]
ミニマムな環境を作ってみました。想定しているのはこんな感じでしょうか？
https://github.com/pnlybubbles-gomibako/dts-test

**Comment by kyasbal-1994** [comment]
@pnlybubbles ありがとう。
でもその環境だと問題があって、例えばプラグインAがプラグインBを参照した際に、Aのビルド結果にBが含まれてしまう。(別々のスクリプトファイルとして生成されるべき)
そこで、考えたのが中身が`window.GrimoireJS.Lib.Path.To.Module`のようなものに置き換えられているようなjsファイルを読み込ませて、実際には外部参照するようにしたらどうかっていうのが今の考え。
もう一つの大きな課題が、interfaceのエクスポート。importしたものを変数に代入することができないから、オブジェクトからの参照で対象を取ることができない。

**Comment by kyasbal-1994** [comment]
また、Typescriptでは変数に代入されているのが明らかにコンストラクタだったとしても、それをクラス型の**型**を意味する識別子として使うことはできない。打開策としてtypeofがあるが、インターフェースには用いれないし、プラグイン全てで外部参照をする際にtypeofを書くのは幾分馬鹿馬鹿しい。

**Comment by kyasbal-1994** [comment]
かなり実装はぐちゃぐちゃだけど一応動きそうなレベルまでは持ってこれた。

**Comment by kyasbal-1994** [comment]
あとはfundamental側で置き換えてみて動作を確認し、うまくいくようなら少しリファクタリングして完成予定。

**Comment by kyasbal-1994** [comment]
現状の問題を整理しつつここにまとめようと思う。

**問題1(Typescriptのインターフェースを値としては代入できない)**

少し当たり前の話なのではあるが、前のコメントで示したimportの文法にはいくつか問題がある。
例えば、`grimoirejs`の公開するどの参照元のライブラリもおそらく使うであろう`IAttributeDeclaration`インターフェースは前の記述法だと以下のようなアクセスをすることになる。

```typescript
const IAttributeDeclaration = gr.Node.IAttributeDeclaration;
```

しかし、これでは問題がある。そもそもjsに出力されることがないTypescriptの型は値に代入することができない。

一方で、コンストラクタさえ存在すればTypescriptの仕様に書かれている`Type Query`を用いて以下のように解決することはできる。

```typescript
const Component = gr.Node.Component;

class SomeComponent extends typeof Component // 型に存在するtypeofはType Query
{

}
```

クラスに対しても型に対して用いる時はtypeofをつけなくてはならないのは面倒であるし、インターフェースがそもそも使えないのはかなり辛い。Typescriptの恩恵をライブラリのビルド環境が原因で制限するのは良くないのでこの案は原理的に難しいとわかった。

**問題1への回避策**

問題1への回避策として、以前の解法に近い方法で以下のようなimportを用いるような方法はどうかと考案した。

```typescript
import IAttributeDeclaration from "grimoirejs/Node/IAttributeDeclaration";
```

結局のところ、`lib`が`ref`になっただけで何の変化もないように見える。もっとも、Typescript上では参照しているd.tsは同一のファイルであるし、何の変化もない。しかし、一方で同時に生成されるjsファイルを以下のようなものに差し替えた。

```javascript
export default window.GrimoireJS.Node.IAttributeDeclaration;
```

そもそも、インターフェースはコンパイル後のjavascriptでは削除されるし、参照されることはないのでこのようなundefinedに常になることが想定されているjavascriptを生成するのは問題ない。
一方で、index.tsをうまく生成すれば、クラスなどの定義やその他のexportはこの部分に実際の参照が入るので問題なく参照解決ができるだろう。

さて、上記のようなjsを生成する場合import元からさんしょうしてもバンドリングされたとして`window.GrimoireJS`の存在を前提とするし、参照しているプラグインや本体をバンドリングに含めることはない。

そこで以下のようなimportを最初に読み込んであげると、その時点でライブラリのタグなどの登録処理を行う部分を呼び出して登録する。また、これをプログラムの中に書くということは、バンドリングするときには対象のライブラリを含めるということだ。

```typescript
import "grimoirejs/register";
```

**問題2(外部解決のクラス参照のデフォルトexportでの利用)**

仮に問題1を上記の方法で解決していったとしても、index.tsの生成には少々の問題がつきまとう。

もし、ユーザーが作成したクラス群の中に`grimoirejs`から取得した型を継承元、引数型、返り値型などに用いると、privateメンバをdefaultエクスポートに記述しているとしているように認識されるためコンパイルエラーとなる。

```
ERROR in ./src/index.ts
(238,1): error TS4082: Default export of the module has or is using private name 'Attribute'.
```

ユーザーが手動で上記のクラスをimportすればこの問題は解決するが、実際にどの参照をimportしなければいけないのかというのはコンパイルして見るまでわからないし、これだけ大量の参照を扱うとなれば手動で行うのは非現実的。

**問題2への回避策(試行中)**

問題2への回避策として、そもそもTypescript側からのライブラリへの参照は必ずimportを用いて、`gr.Node.Components`などを用いらないという制約を設ければ問題ない。この場合、index.tsでは、main.tsの出力する型だけを型として出すことで解決することができる。
しかし一方でTypescriptから参照した際には、この型は認識されない。

ちょっと微妙な感じは否めないが、仕方ないか。

**その他小問題**

* Webpackのraw-loaderはうまく動くが、typescriptは当然だがそれに対してd.tsを出力しないのでWebpackで落ちる。

**Comment by pnlybubbles** [comment]
わたしも考えてみました。この前のを更新しました。
https://github.com/pnlybubbles-gomibako/dts-test

**Comment by pnlybubbles** [comment]
私のほうの現状

#### さまりん

- クラス等の露出はindex.tsでいままでのパッケージと同様、名前つきexport、default export
- commonjs形式でnpmへ
- 使うときは普通にエントリから、名前付きimport, default import
- まだindexの自動生成タスクは無い(grとかの置き方とか)
- jsだけで書いた人用のd.tsは考えてない
- npmのcommonjs出力とは別にscriptタグ用のバンドル出力
- 特定の接頭辞がつくモジュールはバンドルされず、グローバルから依存解決
- スクリプトタグで依存順に読み込み

#### クラス等の露出

名前付きexportでエントリから下のように公開。このindex.tsを自動生成(このタスクは無い)。

```typescript
import Interface from './interface';
import Mod from './mod';
import main from './main';

export {
  Interface,
  Mod,
}

export default main;
```
https://github.com/pnlybubbles-gomibako/dts-test/blob/master/host/src/index.ts

esmodulesを使っているがどっちみちcommonjsに変換。
d.tsも生成してそれを至って普通にnpmに公開する。[[参照]](https://github.com/pnlybubbles-gomibako/dts-test/tree/master/host/lib)

使うときも普通のパッケージと同様。インストールして名前でインポート。

```typescript
import {Interface} from '__prefix__host';
```
https://github.com/pnlybubbles-gomibako/dts-test/blob/master/dep/src/dep-mod.ts#L1

```typescript
import {Mod} from '__prefix__host';
```
https://github.com/pnlybubbles-gomibako/dts-test/blob/master/dep/src/dep-ex-mod.ts#L1

#### scriptタグでの読み込み

npmに公開するコードとは別にscriptタグで読み込むためのバンドリングされたjsを出力する。[[参照]](https://github.com/pnlybubbles-gomibako/dts-test/blob/master/dep/out/bundle.js)

scriptタグで普通に読み込む。今回`__prefix__dep`を読み込むが、これは`__prefix__host`にも依存しているので、両方指定する。

```
<script type="text/javascript" src="/host/out/bundle.js"></script>
<script type="text/javascript" src="/dep/out/bundle.js"></script>
```
https://github.com/pnlybubbles-gomibako/dts-test/blob/master/dep/test/browser/index.html#L5-L6

これはバンドリング時、特定の接頭辞(今は`__prefix__`)が付いているものに関してはバンドルを行いわず、グローバルから依存解決をする。
現状バンドルされたjsはグローバルにpackage.jsonのnameで置かれるがその辺はよしなに(grだけ特殊な置き方にするのとかも)。

```javascript
/* 3 */
/***/ function(module, exports) {

	(function() { module.exports = this["__prefix__host"]; }());

/***/ },
```
https://github.com/pnlybubbles-gomibako/dts-test/blob/master/dep/out/bundle.js#L104

**Comment by kyasbal-1994** [comment]
一応、僕の方は概ね動くようになってしまった。各依存パッケージへの導入や、grimoirejs-mathを少し書き換える必要があること、テスト環境についてはノータッチなことがあるのでまだ少し時間はかかるが、問題と思われていたところは解決した。

実際に、grimoirejs-fundamentalには適用して(mathに関する部分だけnode_modulesに対して修正しなければ現状動かないが)、動作は確認できた。ウォッチ状態ではビルドは2秒前後。
そちらのほうの進捗の中でいいところを使うようにするのがいいと思うけれどその辺どうしようか?

**Comment by pnlybubbles** [comment]
といってもわたし書いたコードこれくらいしかないし、使うでも使わないでもどっちでもよいですよ。
https://github.com/pnlybubbles-gomibako/dts-test/blob/master/host/webpack.config.js

**Comment by kyasbal-1994** [comment]
webpack周りについては僕も最低限しかやってない。
実際にはproduction用と、開発用でタスク分けるべきだと思うけど、その辺あとでブラッシュアップしてくれると嬉しい。Webpackはあくまで最少限度の使い方でしか使ってないから。

**Comment by kyasbal-1994** [comment]
一応、grimoirejs-fundamentalを参照してください。npm run buildで暫定の環境は動くと思う。

**Comment by kyasbal-1994** [comment]
残りのタスク

**grimoirejs**

- [ ] テスト環境修復

**math**

- [ ] 新ビルド環境への移行
- [ ] テスト環境修復
- [ ] Watchタスク

**fundamental**

- [ ] watchタスク挿入
- [ ] Webサーバータスク挿入
- [ ] テスト環境修復
- [ ] registerが動くかどうかのチェック

**forward-shading**

- [ ] 新ビルド環境への差し替え
- [ ] Watchタスク
- [ ] Webサーバータスク導入

**webvr**

- [ ] 新ビルド環境への差し替え
- [ ] Watchタスク
- [ ] Webサーバータスク導入

**gltf**

- [ ] 新ビルド環境への差し替え
- [ ] Watchタスク
- [ ] Webサーバータスク導入

**その他**

- [ ] プロジェクトテンプレートの作成
- [ ] プロジェクトスキャフォルダーの作成

**Comment by kyasbal-1994** [comment]
テンプレートの作成のみになったので、このissueは解決とします。
